language: node_js
before_script:
  - npm install -g gatsby
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - echo "Starting to build ..."
  - echo "Installing deps ..."
  - echo "Cleaning and rebuilding ..."
  - npm run clean
  - npm run build
install:
  - npm install -g firebase-tools
  - cd functions
  - npm install
  - cd ..
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"