language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - echo "Starting to build ..."
  - echo "Installing deps ..."
  - npm run build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"