language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_script:
  - npm i -g gatsby
  - npm i
script:
  - echo "Starting to build ..."
  - echo "Installing deps ..."
  - echo "rebuilding ..."
  - npm run build
install:
  - npm install -g firebase-tools
  - cd functions
  - npm install
  - cd ..
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"